import React, { useContext, useState } from "react";
import { ArrowRight, Mail } from "lucide-react";
import { LangContext } from "./Navbar";

const Contact: React.FC = () => {
  const { lang } = useContext(LangContext);
  const isNl = lang === "nl";
  const t = isNl ? {
    eyebrow: "Je eerste automatiseringskans", title: "Waar verliest je team de meeste tijd?", body: "Vertel ons over één repetitieve taak. We reageren met een concrete eerste gedachte. Geen verkooppraatje.", name: "Naam", email: "Werk e-mail", company: "Bedrijf", task: "Welke taak wil je verminderen?", namePh: "Je naam", emailPh: "naam@bedrijf.nl", companyPh: "Je administratiekantoor", taskPh: "Bijvoorbeeld: ontbrekende documenten opvolgen", button: "Plan mijn gratis workflow call", sending: "Versturen...", success: "Bedankt. We nemen snel contact op.", error: "Verzenden mislukt. Probeer het opnieuw.",
  } : {
    eyebrow: "Your first automation opportunity", title: "Where does your team lose the most time?", body: "Tell us about one repetitive task. We will reply with a concrete first thought. No sales script.", name: "Name", email: "Work email", company: "Company", task: "What task would you like to reduce?", namePh: "Your name", emailPh: "name@company.com", companyPh: "Your bookkeeping firm", taskPh: "For example: chasing missing documents", button: "Book my free workflow call", sending: "Sending...", success: "Thanks. We will get back to you soon.", error: "Something went wrong. Please try again.",
  };
  const [form, setForm] = useState({ name: "", email: "", company: "", task: "" });
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus("sending"); try { const response = await fetch("https://formspree.io/f/xpwrlllo", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(); setStatus("success"); setForm({ name: "", email: "", company: "", task: "" }); } catch { setStatus("error"); } };
  return <section id="contact" className="bg-white py-24 lg:py-32"><div className="container mx-auto px-4 md:px-6"><div className="overflow-hidden rounded-[2rem] bg-[#f3e6dc] shadow-[0_25px_80px_rgba(61,46,37,0.1)]"><div className="grid lg:grid-cols-[0.82fr_1.18fr]"><div className="relative p-7 sm:p-10 lg:p-14"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#e6a58a]/40 blur-3xl" aria-hidden="true" /><div className="relative"><div className="eyebrow">{t.eyebrow}</div><h2 className="mt-5 max-w-md font-manrope text-4xl font-bold leading-[1.03] tracking-[-0.035em] text-[#211e20] sm:text-5xl">{t.title}</h2><p className="mt-6 max-w-md text-base leading-relaxed text-[#6f615a]">{t.body}</p><a href="mailto:contact@rockpeach.io" className="mt-10 inline-flex items-center gap-2 text-sm font-bold text-[#8e452d] hover:text-[#5f2d1e]"><Mail size={17} />contact@rockpeach.io</a></div></div><div className="bg-white p-5 sm:p-8 lg:p-10"><form onSubmit={submit} className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><label>{t.name}<input name="name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder={t.namePh} required /></label><label>{t.email}<input name="email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder={t.emailPh} required /></label></div><label>{t.company}<input name="company" value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} placeholder={t.companyPh} required /></label><label>{t.task}<textarea name="task" rows={5} value={form.task} onChange={(e) => setForm({ ...form, task: e.target.value })} placeholder={t.taskPh} required /></label>{status === "success" && <p className="text-sm font-semibold text-emerald-700">{t.success}</p>}{status === "error" && <p className="text-sm font-semibold text-red-700">{t.error}</p>}<button type="submit" disabled={status === "sending"} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-[#191b20] px-5 py-4 text-base font-bold text-white transition hover:bg-[#34343a] disabled:opacity-60">{status === "sending" ? t.sending : t.button}<ArrowRight size={18} /></button></form></div></div></div></div></section>;
};
export default Contact;
