import React, { useContext } from "react";
import { ArrowUpRight, FileText, Inbox, ListChecks, MessageSquareText } from "lucide-react";
import { LangContext } from "./Navbar";

const Services: React.FC = () => {
  const { lang } = useContext(LangContext); const isNl = lang === "nl";
  const t = isNl ? { eyebrow: "Herkenbaar werk. Praktische automatisering.", title: "Begin met het proces dat elke maand blijft terugkomen.", body: "Geen generieke AI-tool bovenop je werk. We begrijpen eerst waar tijd weglekt en bouwen daarna een workflow rondom je bestaande software.", before: "Nu", after: "Met Rockpeach" } : { eyebrow: "Recognizable work. Practical automation.", title: "Start with the process that keeps coming back every month.", body: "No generic AI tool bolted onto your work. We first understand where time leaks out, then build a workflow around the software you already use.", before: "Today", after: "With Rockpeach" };
  const cases = isNl ? [
    { icon: FileText, title: "Ontbrekende documenten", before: "Medewerkers sturen handmatig herinneringen en houden antwoorden bij in losse inboxen.", after: "Persoonlijke herinneringen worden voorbereid en openstaande documenten blijven zichtbaar.", result: "Completere klantdossiers, eerder in de maand." },
    { icon: Inbox, title: "Inboxtriage", before: "Berichten, bijlagen en vragen komen binnen zonder duidelijke eigenaar of volgende stap.", after: "Berichten worden gesorteerd, context wordt toegevoegd en conceptantwoorden staan klaar.", result: "Snellere reacties met minder schakelen." },
    { icon: ListChecks, title: "Klantstatus & deadlines", before: "Opvolging leeft in spreadsheets, hoofden en verschillende tools.", after: "Een gedeeld overzicht maakt pendings en deadlines per klant zichtbaar.", result: "Minder verrassingen, rustiger werk." },
    { icon: MessageSquareText, title: "Onboarding van nieuwe klanten", before: "Informatie komt gefaseerd binnen en het team jaagt op ontbrekende context.", after: "Een gestructureerde intake verzamelt wat nodig is voordat het werk start.", result: "Een voorspelbaarder proces vanaf dag één." },
  ] : [
    { icon: FileText, title: "Missing documents", before: "Teams send reminders manually and track replies across separate inboxes.", after: "Personalized reminders are prepared and outstanding documents stay visible.", result: "More complete client files, earlier in the month." },
    { icon: Inbox, title: "Inbox triage", before: "Messages, attachments and questions arrive without a clear owner or next step.", after: "Messages are sorted, context is added and draft replies are ready.", result: "Faster responses with less back-and-forth." },
    { icon: ListChecks, title: "Client status & deadlines", before: "Follow-ups live in spreadsheets, people’s heads and different tools.", after: "A shared view makes pending work and deadlines visible by client.", result: "Fewer surprises, calmer operations." },
    { icon: MessageSquareText, title: "New client onboarding", before: "Information arrives in pieces and the team chases missing context.", after: "A structured intake gathers what is needed before work starts.", result: "A more predictable process from day one." },
  ];
  return <section id="use-cases" className="relative bg-white py-24 lg:py-32"><div className="container mx-auto px-4 md:px-6"><div className="grid gap-7 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><div className="eyebrow">{t.eyebrow}</div><h2 className="mt-5 max-w-2xl font-manrope text-4xl font-bold leading-[1.02] tracking-[-0.035em] text-[#191b20] sm:text-5xl">{t.title}</h2></div><p className="max-w-xl text-lg leading-relaxed text-[#66645f] lg:justify-self-end">{t.body}</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{cases.map(({ icon: Icon, title, before, after, result }) => <article key={title} className="group rounded-[1.4rem] border border-[#e8e2db] bg-[#fcfaf7] p-6 transition hover:-translate-y-1 hover:border-[#d4b4a2] hover:shadow-[0_18px_45px_rgba(56,41,31,0.08)]"><div className="flex items-start justify-between gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f2ded3] text-[#a95232]"><Icon size={20} /></div><ArrowUpRight size={18} className="text-[#b9b0a8] transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#a95232]" /></div><h3 className="mt-6 font-manrope text-xl font-bold text-[#202125]">{title}</h3><div className="mt-5 space-y-4 text-sm leading-relaxed"><div><div className="text-[0.63rem] font-bold uppercase tracking-[0.16em] text-[#9b938a]">{t.before}</div><p className="mt-1.5 text-[#74716c]">{before}</p></div><div className="border-t border-[#e9e2db] pt-4"><div className="text-[0.63rem] font-bold uppercase tracking-[0.16em] text-[#a95232]">{t.after}</div><p className="mt-1.5 text-[#4a4844]">{after}</p></div></div><div className="mt-6 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-[#2b2b2c]"><span className="mr-2 text-[#a95232]">→</span>{result}</div></article>)}</div></div></section>;
};
export default Services;
